### ISSUE TITLE
How to access object?

### ISSUE THREAD

**Issue by Wolfr** [Wolfr/clank#5]
Q:

I have integrated cookies in this angular test code, the idea is that you can click a link and it will set a cookie.

This cookie stores your device name so we can save it so it doesn't always reset to the default device

https://github.com/Wolfr/angtest/blob/cookies/js/controllers.js

Now I was wondering, if the cookie reads 'iPhone 5', how to set the right object to $scope.devices?

**Comment by rubenv** [comment]
Fixed!
