### ISSUE TITLE
Cookie for saving device orientation

### ISSUE THREAD

**Issue by Wolfr** [Wolfr/clank#6]
So I got the code for cookies working:

```
// When you set a device, also set a cookie
$scope.saveDeviceChoice = function() {
  console.log($scope.deviceChoice.name);

  console.log('We changed the device');
  $cookieStore.put('savedDevice', $scope.deviceChoice.name);
  console.log('Our cookie now reads ' +  $cookieStore.get('savedDevice'));
}
```

But logging $scope.savedDeviceOrientations.name returns undefined

I am doing some logs to see what is going on.

```
// @todo This code is exactly like save device but breaks?
$scope.saveDeviceOrientation = function() {
  console.log($scope.deviceOrientations.name);

  console.log('We changed the orientation');
  $cookieStore.put('savedOrientation', $scope.deviceOrientations.name);
  console.log('Our cookie now reads ' +  $cookieStore.get('savedOrientation'));

}
```

No idea why one is defined and the other isn't, they both have a model and the data is defined in the controller js file.

To be clear whenever you select a device or orientation it should get saved to a cookie.

**Comment by rubenv** [comment]
You have an `s` too much:

![screenshot_29_05_13_08_34](https://f.cloud.github.com/assets/42904/577184/f1691884-c829-11e2-8c50-6d30eace7941.png)

**Comment by rubenv** [comment]
Note the difference between the available options `$scope.deviceOrientations`, which is an array and the selected item `$scope.deviceOrientation`, which is an object. Rename the latter to `$scope.selectedOrientation` if you want to make things clearer.

**Comment by Wolfr** [comment]
Fixed it with omitting the s.

Changing `$scope.deviceOrientation` would mean the ng-model would also need to be selectedOrientation, this breaks some other code. I couldn't figure it out in a couple of minutes.

What is sure is that I have to get more used to naming conventions between models & controllers.
