### ISSUE TITLE
Use Angular in full - opinion wanted

### ISSUE THREAD

**Issue by Wolfr** [Wolfr/clank#80]
@rubenv 
- Would it be a good idea to use Angular for mobile web apps genre forecast.io?
- Thus the router of angular could be used to switch between screens - using `ng-animate` for transitions?
- The jquery pjax ( https://github.com/defunkt/jquery-pjax ) and push.js http://maker.github.io/ratchet/#push are flaky - they handle updating of HTML content but what you really want is pre/post event hooks etc. so you can control your app the way you want it (e.g. what if you want to call an alert right after you enter a new view?)

**Comment by rubenv** [comment]
Little tied up right now, but I will get back to you on this soon.
