### ISSUE TITLE
Can't find this mixin: pie-clearfix

### ISSUE THREAD

**Issue by mattkatz** [Wolfr/clank#92]
@include pie-clearfix; 
//where is this to be imported?

**Comment by Wolfr** [comment]
This is part of Compass

You need to have compass installed
http://compass-style.org/

**Comment by mattkatz** [comment]
Ah - I figured that out.
I'm trying to use clank on codepen to doodle some mobile interfaces.
http://codepen.io/mttktz/pen/Lisgv
I think the codepen scss already has compass installed so I'm just going to define the pie-clearfix mixin as blank earlier in the scss.  
This seems to fix it.
